#+TITLE: 気象庁データにおける場所に関する情報の扱い方
#+DATE: [2022-02-25 Fri]
#+AUTHOR: AKIYAMA Kouhei

* 情報源
** 発表区域情報
:PROPERTIES:
:CUSTOM_ID: common-area-json
:END:

URL: https://www.jma.go.jp/bosai/common/const/area.json

[[https://www.jma.go.jp/jma/kishou/know/saibun/][気象庁 | 気象警報・注意報や天気予報の発表区域]]に対応する情報。日本全国を5階層に分割している。用語の定義は左記リンク先を参照のこと。

#+begin_src elisp
;; (jma-json-get "https://www.jma.go.jp/bosai/common/const/area.json")の結果:
(
 ;; 地方予報区(11区)
 (centers
  (\010100 (name . "北海道地方") (enName . "Hokkaido") (officeName . "札幌管区気象台") (children . ["011000" "012000" "013000" "014030" "014100" "015000" "016000" "017000"]))
  (\010200 (name . "東北地方") (enName . "Tohoku") (officeName . "仙台管区気象台") (children . ["020000" "030000" "040000" "050000" "060000" "070000"]))
  ...)

 ;; 府県予報区(58区)
 (offices
  (\011000 (name . "宗谷地方") (enName . "Soya") (officeName . "稚内地方気象台") (parent . "010100") (children . ["011000"]))
  (\012000 (name . "上川・留萌地方") (enName . "Kamikawa Rumoi") (officeName . "旭川地方気象台") (parent . "010100") (children . ["012010" "012020"]))
  ...)

 ;; 一次細分区域(142区)
 (class10s
  (\011000 (name . "宗谷地方") (enName . "Soya Region") (parent . "011000") (children . ["011011" "011012" "011013"]))
  (\012010 (name . "上川地方") (enName . "Kamikawa Region") (parent . "012000") (children . ["012011" "012012" "012013"]))
  ...)

 ;; 市町村等をまとめた地域(375区)
 (class15s
  (\011011 (name . "宗谷北部") (enName . "Northern Soya") (parent . "011000") (children . ["0121400" "0151100" "0151600" "0152000"]))
  (\011012 (name . "宗谷南部") (enName . "Southern Soya") (parent . "011000") (children . ["0151200" "0151300" "0151400"]))
  ...)

 ;; 二次細分区域(1776区)
 (class20s
  (\0110000 (name . "札幌市") (enName . "Sapporo City") (kana . "さっぽろし") (parent . "016012"))
  (\0120200 (name . "函館市") (enName . "Hakodate City") (kana . "はこだてし") (parent . "017012"))
  ...)
)
#+end_src

エリアコードは階層内でのみ一意であることに注意。例えば011000は「宗谷地方」だが、それが府県予報区と次細分区域のどちらを指しているかはコードだけでは判別できない。

異なる階層でも同じ名称(同じ範囲を表すもの)には同じコードを付ける傾向がある。全てそうなっているかは未確認。

二次細分区域の説明には「[[https://www.jma.go.jp/jma/kishou/know/saibun/][市町村（東京特別区は区）を原則としますが、一部市町村を分割して設定している場合があります。]]」とあるので、概ね市区町村名からそれが属する全階層の区域を求めることができる。ただし「○○市北部」のような名称もあるので注意。

** 府県予報区と府県天気予報の予報区との対応関係
:PROPERTIES:
:CUSTOM_ID: forecast-area-json
:END:

URL: https://www.jma.go.jp/bosai/forecast/const/forecast_area.json

府県予報区内の天気予報を行う予報区(一次細分区域)とアメダス観測所の一覧。

#+begin_src elisp
;;(jma-json-get "https://www.jma.go.jp/bosai/forecast/const/forecast_area.json")の結果(58区):
(
 ;; 府県予報区 class10=一次細分区域 amedas=アメダス観測所 class20=二次細分区域(何の?)
 (\011000 . [((class10 . "011000") (amedas . ["11016"]) (class20 . "0121400"))])
 (\012000 . [((class10 . "012010") (amedas . ["12442"]) (class20 . "0120400"))
             ((class10 . "012020") (amedas . ["13277"]) (class20 . "0121200"))])
 (\013000 . [((class10 . "013010") (amedas . ["17341"]) (class20 . "0121100"))
             ((class10 . "013020") (amedas . ["17521"]) (class20 . "0120801"))
             ((class10 . "013030") (amedas . ["17112"]) (class20 . "0121900"))])
 ...以下amedasが複数あるものを全て抜粋...
 (\020000 . [((class10 . "020010") (amedas . ["31312" "31436" "31461"]) (class20 . "0220100"))
 ...
 (\030000 . [((class10 . "030010") (amedas . ["33431" "33071" "33911"]) (class20 . "0320100"))
 ...
 (\040000 . [((class10 . "040010") (amedas . ["34392" "34292" "34216"]) (class20 . "0410001"))
 ...
             ((class10 . "050020") (amedas . ["32126" "32596"]) (class20 . "0521300"))])
 ...
 (\070000 . [((class10 . "070010") (amedas . ["36127" "36667" "36476"]) (class20 . "0720100"))
             ((class10 . "070020") (amedas . ["36846" "36151"]) (class20 . "0720400"))
             ((class10 . "070030") (amedas . ["36361" "36641"]) (class20 . "0720200"))])
 ...
 (\150000 . [((class10 . "150010") (amedas . ["54232" "54421"]) (class20 . "1510000"))
             ((class10 . "150020") (amedas . ["54501" "54841"]) (class20 . "1520200"))
 ...
 (\180000 . [((class10 . "180010") (amedas . ["57066" "57121"]) (class20 . "1820100"))
 ...
             ((class10 . "200020") (amedas . ["48361" "48491" "48331"]) (class20 . "2020201"))
 ...
             ((class10 . "220020") (amedas . ["50281" "50561"]) (class20 . "2220500"))
 ...
             ((class10 . "220040") (amedas . ["50456" "50551"]) (class20 . "2213001"))])
 ...
 (\240000 . [((class10 . "240010") (amedas . ["53133" "53061" "53112"]) (class20 . "2420100"))
 ...
 (\280000 . [((class10 . "280010") (amedas . ["63518" "63576" "63571" "63383"]) (class20 . "2810000"))
 ...
 (\340000 . [((class10 . "340010") (amedas . ["67437" "67511" "67401"]) (class20 . "3410000"))
 ...
 (\360000 . [((class10 . "360010") (amedas . ["71106" "71066"]) (class20 . "3620100"))
 ...
             ((class10 . "380020") (amedas . ["73136" "73141"]) (class20 . "3820500"))
 ...
 (\450000 . [((class10 . "450010") (amedas . ["87376" "87492"]) (class20 . "4520100"))
 ...
 (\460040 . [((class10 . "460040") (amedas . ["88836" "88971"]) (class20 . "4622200"))])
 (\460100 . [((class10 . "460010") (amedas . ["88317" "88061" "88466"]) (class20 . "4620100"))
 ...)
#+end_src

一次細分区域内に気温の予報を行うアメダス観測所が複数存在する場合がある。

アメダス観測所が複数ある場合、より下位の区域(例えば二次細分区域)との対応関係の情報は無い。気象庁のWebサイトでも、市を選択しても気温の予報は一つに絞り込まれない。例えば津軽(class10=020010)には三つのアメダス観測所(青森31312, 深浦31436, 弘前31461)が存在する。中泊町(class20=0238700)は津軽の一部だが、[[https://www.jma.go.jp/bosai/forecast/#area_type=class20s&area_code=0238700][Webサイト]]を開いても三つの内のどのアメダス観測所を参照すべきかは明確には示されない。JSONにも対応情報は無い。中泊町は北五津軽(class15=020012)に属するが、三つのアメダス観測所はいずれも北五津軽には無い。強いて言えば緯度経度情報から最も近いものを選ぶくらいしかない。近所にある複数のアメダス観測所の予報を複合的に見て判断しろという事なのかもしれない。

** 府県予報区と府県週間天気予報の予報区との対応関係
:PROPERTIES:
:CUSTOM_ID: forecast-week-area-json
:END:

URL: https://www.jma.go.jp/bosai/forecast/const/week_area.json

府県予報区内の週間予報区域(府県週間天気予報のために細分化された区域)の一覧。

#+begin_src elisp
;;(jma-json-get "https://www.jma.go.jp/bosai/forecast/const/week_area.json")の結果(58区):
(
 ;; 府県予報区       一次細分区域      週間予報区域        アメダス観測所
 ;; 千葉県           北東部            千葉県              銚子
 (\120000 . [((srf . "120020") (week . "120000") (amedas . "45147"))])
 ;; 静岡県           中部              静岡県              静岡
 (\220000 . [((srf . "220010") (week . "220000") (amedas . "50331"))])
 ;; 岐阜県           美濃地方          岐阜県              岐阜
 (\210000 . [((srf . "210010") (week . "210000") (amedas . "52586"))
 ;;                  美濃地方          岐阜県美濃地方      岐阜    (↑季節細分)
             ((srf . "210010") (week . "210010") (amedas . "52586"))
 ;;                  飛騨地方          岐阜県飛騨地方      高山    (↑季節細分)
             ((srf . "210020") (week . "210020") (amedas . "52146"))])
 ...
 ;; 長野県           北部              長野県              長野
 (\200000 . [((srf . "200010") (week . "200000") (amedas . "48156"))
 ;;                  北部              長野県北部          長野    (↑季節細分)
             ((srf . "200010") (week . "200010") (amedas . "48156"))
 ;;                  中部              長野県中部・南部    松本    (↑季節細分)
             ((srf . "200020") (week . "200100") (amedas . "48361"))])
 ...
 ;; 東京都           東京地方          東京地方            東京    (常時細分)
 (\130000 . [((srf . "130010") (week . "130010") (amedas . "44132"))
 ;;                  伊豆諸島南部      伊豆諸島            八丈島  (常時細分)
             ((srf . "130030") (week . "130100") (amedas . "44263"))
 ;;                  伊豆諸島北部      伊豆諸島北部        大島      (↑季節細分)
             ((srf . "130020") (week . "130020") (amedas . "44172"))
 ;;                  伊豆諸島南部      伊豆諸島南部        八丈島    (↑季節細分)
             ((srf . "130030") (week . "130030") (amedas . "44263"))
 ;;                  小笠原諸島        小笠原諸島          父島    (常時細分)
             ((srf . "130040") (week . "130040") (amedas . "44301"))])
 ...)
#+end_src

srfの意味は不明。一次細分区域のコード。地域を代表する一次細分区域？ アメダス観測所がある一次細分区域？

[[https://www.jma.go.jp/jma/kishou/know/kurashi/shukan.html][気象庁｜週間天気予報の解説]]に書かれている通り、地理的な理由で常時細分化されている地域や季節的な理由で一時的に細分化されている地域がある。従って配列の中の全ての地域が予報で常に使われるわけではない。

** 一次細分区域と府県週間天気予報の予報区との対応関係
:PROPERTIES:
:CUSTOM_ID: forecast-week-area05.json
:END:

URL: https://www.jma.go.jp/bosai/forecast/const/week_area05.json

一次細分区域がどの週間予報区域(府県週間天気予報のために細分化された区域)に対応しうるかの対応表。

#+begin_src elisp
;;(jma-json-get "https://www.jma.go.jp/bosai/forecast/const/week_area05.json")の結果(142区):
(
 ;; 一次細分区域 [週間予報区域...]
 ;; 北西部   千葉県
 (\120010 . ["120000"])
 ;; 北東部   千葉県
 (\120020 . ["120000"])
 ;; 南部     千葉県
 (\120030 . ["120000"])
 ;; 中部     静岡県
 (\220010 . ["220000"])
 ;; 伊豆     静岡県
 (\220020 . ["220000"])
 ;; 東部     静岡県
 (\220030 . ["220000"])
 ;; 西部     静岡県
 (\220040 . ["220000"])
 ;; 美濃地方 岐阜県 岐阜県美濃地方
 (\210010 . ["210000" "210010"])
 ;; 飛騨地方 岐阜県 岐阜県飛騨地方
 (\210020 . ["210000" "210020"])
 ...
 ;; 北部     長野県 長野県北部
 (\200010 . ["200000" "200010"])
 ;; 中部     長野県 長野県中部・南部
 (\200020 . ["200000" "200100"])
 ;; 南部     長野県 長野県中部・南部
 (\200030 . ["200000" "200100"])
 ...
 ;; 東京地方 東京地方
 (\130010 . ["130010"])
 ;; 伊豆諸島北部 伊豆諸島 伊豆諸島北部
 (\130020 . ["130100" "130020"])
 ;; 伊豆諸島南部 伊豆諸島 伊豆諸島南部
 (\130030 . ["130100" "130030"])
 ;; 小笠原諸島 小笠原諸島
 (\130040 . ["130040"])
 ...)
#+end_src

一次細分区域が属する週間予報区域は[[https://www.jma.go.jp/jma/kishou/know/kurashi/shukan_saibun.html][気象庁｜週間天気予報の季節細分についての解説]]に書かれている通り季節によって変わりうる。配列は可能性のあるものを全て列挙している。

** 二次細分区域の緯度経度範囲
:PROPERTIES:
:CUSTOM_ID: common-class20relm-json
:END:

URL: https://www.jma.go.jp/bosai/common/const/class20relm.json

おそらく二次細分区域を内包する緯度経度範囲。

#+begin_src elisp
;;(jma-json-get "https://www.jma.go.jp/bosai/common/const/class20relm.json")の結果(1772区)
(
 ;; ne=北東角 sw=南西角 parent=市町村等をまとめた地域(class15)
 (\0110000 (name . "札幌市") (ne . [43.1894 141.5054]) (sw . [42.7807 140.9905]) (parent . "016012"))
 (\0120200 (name . "函館市") (ne . [42.0094 141.1874]) (sw . [41.71 140.6924]) (parent . "017012"))
 ...)
#+end_src

** 二次細分区域とアメダス観測所の対応リスト
:PROPERTIES:
:CUSTOM_ID: amedas-class20-list-json
:END:

URL: https://www.jma.go.jp/bosai/amedas/const/amedas_class20_list.json

二次細分区域(概ね市区町村)とアメダス観測所の対応リスト。

#+begin_src elisp
;;(jma-json-get "https://www.jma.go.jp/bosai/amedas/const/amedas_class20_list.json")の結果(1776区):
(
 ;; 札幌市    山口 手稲山 札幌 小金湯 石狩
 (\0110000 . ["14116" "14157" "14163" "14191" "14121"])
 ;; 函館市    川汲 函館 高松 戸井泊 北斗
 (\0120200 . ["23206" "23232" "23281" "23291" "23226"])
 ;; 小樽市    小樽 山口 手稲山 赤井川 余市
 (\0120300 . ["16091" "14116" "14157" "16126" "16076"])
 ;; 旭川市    江丹別 旭川 瑞穂 東神楽 東川
 (\0120400 . ["12386" "12442" "12457" "12501" "12451"])
 ...
 ;; 立川市    所沢 府中 八王子 青梅 飯能
 (\1320200 . ["43266" "44116" "44112" "44056" "43231"])
 ;; 武蔵野市  練馬 府中 世田谷 所沢 東京
 (\1320300 . ["44071" "44116" "44126" "43266" "44132"])
 ;; 三鷹市    練馬 世田谷 府中 東京 日吉
 (\1320400 . ["44071" "44126" "44116" "44132" "46061"])
 ;; 青梅市    青梅 飯能 小沢 所沢 八王子
 (\1320500 . ["44056" "43231" "44051" "43266" "44112"])
 ;; 府中市    府中 練馬 世田谷 所沢 相模原中央
 (\1320600 . ["44116" "44071" "44126" "43266" "46046"])
 ...
 ;; 御蔵島村  三宅坪田 三宅島 神津島
 (\1338200 . ["44228" "44226" "44216"])
 ;; 八丈町    八重見ヶ原 八丈島
 (\1340100 . ["44262" "44263"])
 ;; 青ヶ島村  青ヶ島
 (\1340200 . ["44281"])
 ...
 ;; 高山市    栃尾 清見 高山 丹生川 六厩 船山 宮之前
 (\2120300 . ["52111" "52137" "52146" "52152" "52181" "52192" "52196"])
 ...)
#+end_src

おそらく付近の観測所を並べたもの。

天気予報・週間天気予報で使うアメダス観測所が含まれているとは限らない。

** アメダス観測所リスト
:PROPERTIES:
:CUSTOM_ID: amedas-amedastable-json
:END:

URL: https://www.jma.go.jp/bosai/amedas/const/amedastable.json

アメダス観測所(地域気象観測所)の一覧。アメダスに関する説明は[[https://www.jma.go.jp/jma/kishou/know/amedas/kaisetsu.html#:~:text=%E3%82%A2%E3%83%A1%E3%83%80%E3%82%B9%E3%81%AF1974%E5%B9%B411,%E3%81%95%E3%82%82%E8%A6%B3%E6%B8%AC%E3%81%97%E3%81%A6%E3%81%84%E3%81%BE%E3%81%99%E3%80%82][気象庁 | アメダス]]を参照のこと。

#+begin_src elisp
;;(jma-json-get "https://www.jma.go.jp/bosai/amedas/const/amedastable.json")の結果(1286箇所):
(
 (\11001 (type . "C") (elems . "11112010") (lat . [45 31.2]) (lon . [141 56.1]) (alt . 26) (kjName . "宗谷岬") (knName . "ソウヤミサキ") (enName . "Cape Soya"))
 (\11016 (type . "A") (elems . "11111111") (lat . [45 24.9]) (lon . [141 40.7]) (alt . 3) (kjName . "稚内") (knName . "ワッカナイ") (enName . "Wakkanai"))
 (\11046 (type . "C") (elems . "11112010") (lat . [45 18.3]) (lon . [141 2.7]) (alt . 65) (kjName . "礼文") (knName . "レブン") (enName . "Rebun"))
 ...)
#+end_src

位置情報としては、緯度、経度、高度を含む。

* 市区町村から天気予報のエリアコードを求める方法

天気予報のJSON( =https://www.jma.go.jp/bosai/forecast/data/forecast/<office>.json= )から特定の場所の天気予報を取り出すには次の5つのエリアコードが必要となる。

- 府県予報区コード(office)
- 一次細分区域コード(class10)
- アメダス観測所コード(amedas)
- 週間予報区域コード(week)
- アメダス観測所コード(週間予報用)(amedas-week)

市区町村からこれらのエリアコードを求めるには、次のようにする。(A→Bは上URLの情報を使って、AのコードからBのコードを求めることを意味する)

1. https://www.jma.go.jp/bosai/common/const/area.json ([[#common-area-json][発表区域情報]])
   1. class20→class15
   2. class15→class10(天気予報(詳細)を求めるのに使うコード)
   3. class10→office(ダウンロードするURLを求めるのに使うコード)
2. https://www.jma.go.jp/bosai/forecast/const/forecast_area.json ([[#forecast-area-json][府県予報区と府県天気予報の予報区との対応関係]])
   1. class10→amedas(気温を求めるのに使うコード)

      *注意:複数のアメダス観測所が存在する区域がある。一つに絞り込む簡単な方法は見当たらない。また、安易に絞り込んで良いのかも分からない。*
3. https://www.jma.go.jp/bosai/forecast/const/week_area05.json ([[#forecast-week-area05.json][一次細分区域と府県週間天気予報の予報区との対応関係]])
   1. class10→week(可能性のあるもの複数) (週間天気予報を求めるのに使うコード)
4. https://www.jma.go.jp/bosai/forecast/const/week_area.json ([[#forecast-week-area-json][府県予報区と府県週間天気予報の予報区との対応関係]])
   1. week(可能性のあるもの複数)→amedas(可能性のあるもの複数) (週間天気予報の気温を求めるのに使うコード)

週間天気予報のエリア分けは季節によって変わるので、可能性のあるエリアを全て列挙すること。
